# Generated by Django 5.2.4 on 2025-08-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_profile_options_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='web_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
