# Generated by Django 5.2.4 on 2025-08-06 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_created_at_alter_article_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 5, 17, 15, 641543, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 5, 17, 15, 641563, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 5, 17, 15, 643081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='viewed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 5, 17, 15, 642510, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 5, 17, 15, 642763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 6, 5, 17, 15, 643341, tzinfo=datetime.timezone.utc)),
        ),
    ]
