# Generated by Django 5.2.4 on 2025-08-09 04:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_options_alter_articlerating_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='static/img/placeholder.jpg', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
